/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppPromotionsRouteImport } from './routes/_app/promotions'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProductRouteImport } from './routes/_app/product'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppProductCreateRouteImport } from './routes/_app/product_.create'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductRoute = AppProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppProductCreateRoute = AppProductCreateRouteImport.update({
  id: '/product_/create',
  path: '/product/create',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/orders': typeof AppOrdersRoute
  '/pos': typeof AppPosRoute
  '/product': typeof AppProductRoute
  '/profile': typeof AppProfileRoute
  '/promotions': typeof AppPromotionsRoute
  '/report': typeof AppReportRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/product/create': typeof AppProductCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/orders': typeof AppOrdersRoute
  '/pos': typeof AppPosRoute
  '/product': typeof AppProductRoute
  '/profile': typeof AppProfileRoute
  '/promotions': typeof AppPromotionsRoute
  '/report': typeof AppReportRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/product/create': typeof AppProductCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/product': typeof AppProductRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/report': typeof AppReportRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/orders_/$id': typeof AppOrdersIdRoute
  '/_app/product_/create': typeof AppProductCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/orders'
    | '/pos'
    | '/product'
    | '/profile'
    | '/promotions'
    | '/report'
    | '/settings'
    | '/stock'
    | '/orders/$id'
    | '/product/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/orders'
    | '/pos'
    | '/product'
    | '/profile'
    | '/promotions'
    | '/report'
    | '/settings'
    | '/stock'
    | '/orders/$id'
    | '/product/create'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/orders'
    | '/_app/pos'
    | '/_app/product'
    | '/_app/profile'
    | '/_app/promotions'
    | '/_app/report'
    | '/_app/settings'
    | '/_app/stock'
    | '/_app/orders_/$id'
    | '/_app/product_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product': {
      id: '/_app/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AppProductRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product_/create': {
      id: '/_app/product_/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof AppProductCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders_/$id': {
      id: '/_app/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPosRoute: typeof AppPosRoute
  AppProductRoute: typeof AppProductRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppReportRoute: typeof AppReportRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockRoute: typeof AppStockRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppProductCreateRoute: typeof AppProductCreateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPosRoute: AppPosRoute,
  AppProductRoute: AppProductRoute,
  AppProfileRoute: AppProfileRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppReportRoute: AppReportRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockRoute: AppStockRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppProductCreateRoute: AppProductCreateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
